/** @type {import('prettier').Config} */
module.exports = {
  printWidth: 150,
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "^@/components/(.*)$",
    "^@/ui/(.*)$",
    "^@/api/(.*)$",
    "^@/lib/(.*)$",
    "^@/styles/(.*)$",
    "^types$",
    "<THIRD_PARTY_MODULES>",
    "^[./]",
  ],
  tailwindFunctions: ["cn"],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  pluginSearchDirs: false,
  plugins: ["@ianvs/prettier-plugin-sort-imports", require("prettier-plugin-tailwindcss")],
}
